package sys2202.examples.homework3;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;

import sys2202.examples.phtis.LocationDatum;
import sys2202.examples.phtis.simulator.smartphone.Smartphone;

public class Main {

	public static void main(String[] args) throws Exception {

		// Create a server that will receive XML data generated by our simulated smartphone.
		Server server = new Server();
		
		// Create a smartphone and take it for a drive.
		Smartphone smartphone = new Smartphone("msg8u");		
		smartphone.Drive();

		// We've now generated some location data on the smartphone, and the data are stored in 
		// the local data store.
		ArrayList<LocationDatum> locationData = smartphone.getLocalDataStore().getLocationData();
		
		// Let's write the location data to an XML file so that we can send it to a server for further processing.
		// An XML file is started for you below, including the DTD declaration at the top of the XML file. If
		// you haven't done so already, open locations.dtd and type in your DTD for the location data we are working
		// with.
		File xmlFile = new File("src/sys2202/examples/homework3/locations.xml");
		PrintWriter xmlFileWriter = new PrintWriter(xmlFile);
		xmlFileWriter.write("<!DOCTYPE locations SYSTEM \"locations.dtd\">\n");
		
		// YOUR CODE:  Iterate over the location data and write the appropriate XML to the XML file using xmlFileWriter.
		
		// ...
		// ...
		// ...
		
		// Be sure to close your XML file!
		xmlFileWriter.close();
		
		// Send your XML file to the server for processing. Hop over to Server.java and continue working.
		server.processXmlFile(xmlFile);
	}
}