package sys2202.homework3;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;

import sys2202.phtis.LocationDatum;
import sys2202.phtis.simulator.smartphone.Smartphone;

public class Main {

	public static void main(String[] args) throws Exception {

		// Create a server that will receive XML data generated by our simulated smartphone.
		Server server = new Server();
		
		// YOUR CODE:  Create a smartphone, using your UVa ID as the device identifier (i.e., replace the string below with your ID).
		Smartphone smartphone = new Smartphone("YOUR_UVA_ID_HERE");
		
		// Take your smartphone for a drive to generate some location data.
		smartphone.Drive();

		// We've now generated some location data on the smartphone, and the data are stored in 
		// the local data store. Take a look!
		ArrayList<LocationDatum> locationData = smartphone.getLocalDataStore().getLocationData();
		for(int i = 0; i < locationData.size(); ++i) {
			
			LocationDatum location = locationData.get(i);
			System.out.println(location.toString());
			
		}
				
		// Let's write the location data to an XML file so that we can send it to a server for further processing.
		// An XML file is started for you below, including the DTD declaration at the top of the XML file. If
		// you haven't done so already, open locations.dtd and type in your DTD for the location data we are working
		// with.
		File xmlFile = new File("src/sys2202/examples/homework3/locations.xml");
		PrintWriter xmlFileWriter = new PrintWriter(xmlFile);
		xmlFileWriter.write("<!DOCTYPE locations SYSTEM \"locations.dtd\">\n");
		
		// YOUR CODE:  Iterate over the location data and write the appropriate XML to the XML file using xmlFileWriter.
		
		// ...
		// ...
		// ...
		
		// Be sure to close your XML file!
		xmlFileWriter.close();
		
		// Send your XML file to the server for processing. Hop over to Server.java and continue working.
		server.processXmlFile(xmlFile);
	}
}