package sys2202.homework3;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;

import sys2202.phtis.LocationDatum;
import sys2202.phtis.simulation.Simulator;
import sys2202.phtis.simulation.smartphone.Smartphone;

public class Main {

	public static void main(String[] args) throws Exception {

		// Create a server that will receive XML data generated by our simulated smartphone.
		Server server = new Server();
		
		// YOUR CODE:  Create a smartphone, using your UVa ID as the device identifier (i.e., replace msg8u with your ID).
		Smartphone smartphone = new Smartphone("msg8u");
		
		// Create a simulator to do various things with our smartphone.
		Simulator simulator = new Simulator(smartphone);
		
		// Take our smartphone for a drive to generate some location data.
		simulator.driveWithPhone();

		// We've now generated some location data on the smartphone, and the data are stored in 
		// the local data store. Take a look!
		ArrayList<LocationDatum> locationData = smartphone.getLocalDataStore().getLocationData();
		for(int i = 0; i < locationData.size(); ++i) {
			
			LocationDatum location = locationData.get(i);
			System.out.println(location.toString());
			
		}
				
		// Let's write the location data to an XML file so that we can send it to the server for further processing.
		// An XML file is started for you below, including the DTD declaration at the top of the XML file that links
		// your XML file to your DTD. Read each line and make sure you understand what is going on.
		File xmlFile = new File("src/sys2202/examples/homework3/locations.xml");
		PrintWriter xmlFileWriter = new PrintWriter(xmlFile);
		xmlFileWriter.write("<!DOCTYPE locations SYSTEM \"locations.dtd\">\n");
		
		// YOUR CODE:  Iterate over the location data and write all data to the XML file using xmlFileWriter. The XML
		// that you write to the file must conform to your DTD or subsequent steps will not work.
		
		// ...
		// ...
		// ...
		
		// Be sure to close your XML file!
		xmlFileWriter.close();
		
		// Send your XML file to the server for processing. Hop over to Server.java and continue working.
		server.processXmlFile(xmlFile);
	}
}