package sys2202.homework3;

import java.io.File;
import java.io.PrintWriter;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

public class Server {

	/**
	 * The purpose of this method is to process an XML file that contains
	 * location data generated by a smartphone. The specific processing that is
	 * performed is to convert the XML file to JSON and write the JSON to a new
	 * file for long-term storage.
	 * 
	 * @param xmlFile File to process.
	 * @throws Exception
	 */
	public void processXmlFile(File xmlFile) throws Exception {

		// Read the method comment above to understand what we're trying to do here.
		
		// Start a JSON file. We're going to write location data to this file
		// after we extract the location data from the XML file that has been
		// passed into this method.
		File jsonFile = new File("src/sys2202/homework3/locations.json");
		PrintWriter jsonFileWriter = new PrintWriter(jsonFile);

		// Set up an XML parser and parse the XML file that has been passed to
		// this method.
		DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
		documentBuilderFactory.setValidating(true);
		DocumentBuilder documentBuilder = documentBuilderFactory.newDocumentBuilder();
		Document parsedXml = documentBuilder.parse(xmlFile);

		// Iterate through the parsed XML document (parsedXml) and write the equivalent 
		// JSON to file using jsonFileWriter. For example, consider the following XML fragment:
		// 
		// <people>
		//   <person>
		//     <name>Matt</name>
		//   </person>
		// </people>
		//
		// This XML could be written to JSON as the following:
		//
		// [
		//   {
		//     "name":"Matt"
		//   }
		// ]
		//
		// YOUR CODE:  Iterate through the parsed XML document (parsedXml) and write the equivalent 
		// JSON to file using jsonFileWriter.
			NodeList nl = parsedXml.getElementsByTagName("*");
			jsonFileWriter.write("{\n\t\"locations\":{ \n");
			jsonFileWriter.write(" \t\t\"LocationDatum\":[{ \n");
			for(int i = 0; i < nl.getLength(); i++){
				Element el = (Element)nl.item(i);
			
				if(el.getNodeName().contains("LocationDatum")){
					jsonFileWriter.write("\t\t\t\"" + "latitude\":" + "\"" +
				el.getElementsByTagName("latitude").item(0).getTextContent()+ "\"," + "\n");
					jsonFileWriter.write("\t\t\t\"" + "longitude\":" +  "\"" +
							el.getElementsByTagName("longitude").item(0).getTextContent() + "\"," + "\n");
					jsonFileWriter.write("\t\t\t\"" + "accuracy\":" + "\"" +
							el.getElementsByTagName("accuracy").item(0).getTextContent()+ "\","+ "\n");
					jsonFileWriter.write("\t\t\t\"" + "deviceId\":" + "\"" +
							el.getElementsByTagName("deviceId").item(0).getTextContent()+ "\","+ "\n");
					jsonFileWriter.write("\t\t\t\"" + "timestamp\":" + "\"" +
							el.getElementsByTagName("timestamp").item(0).getTextContent()+ "\""+ "\n");
					if(i < 31) {
					jsonFileWriter.write("\t\t\t},{\n");
					}
				}
				
			}
			jsonFileWriter.write("\t\t}] \n");
			jsonFileWriter.write("\t} \n");
			jsonFileWriter.write("} \n");
		// ...
		// ...
		// ...
		
		// Be sure to close your JSON file!
		jsonFileWriter.close();
	}
}